Adds back print styling
Exygy/askdarcel-web pull request #212
Opened 2024-09-18 04:18 UTC by rosschapman

2024-09-18 16:42 UTC, rosschapman commented on .eslintrc.js
> +    "@typescript-eslint/prefer-nullish-coalescing": "warn"
Sneaking this in. Something @adriencyberspace and I discussed liked having.

2024-09-18 21:07 UTC, adriencyberspace requested changes
Can we address the styling issues caused by the search bar being in the navbar in this PR?

1. At smaller desktop screens, user is no longer able to access all nav links (search bar should take up less horizontal space and probably be flex width)
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/171363fd-59d4-4da8-946a-be84ef9c4c7f">
2. There should be 32px gap between Our415 logo and search bar
3. IMO there should be a 120px container around the logo so that the searchbar is always in the same place on the screen (there is something like this around the google translate widget already)
4. nit: searchbar should be same height as logo and with a white background (design changed)

2024-09-19 02:59 UTC, rosschapman commented on .eslintrc.js
> +    "@typescript-eslint/prefer-nullish-coalescing": "warn",
```suggestion
```

2024-09-19 15:24 UTC, rosschapman commented
> Can we address the styling issues caused by the search bar being in the navbar in this PR?

@adriencyberspace Yep, definitely some style issues as things have moved around. I'm going to focus on this separately. Kyle has some new recommendations and spec for the navbar in https://www.notion.so/exygy/Update-mobile-menu-e7a2f2d9d23748baabd943e1f0b2f045?pvs=4.

2024-09-19 15:28 UTC, merged