WIP
Exygy/askdarcel-web pull request #75
Opened 2024-07-05 23:28 UTC by rosschapman

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have assigned reviewers
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2024-07-08 22:24 UTC, adriencyberspace requested changes
I'm currently blocked on being able to create a 2-tiered navigation but a couple of things I'm seeing right now:

1. If you have two dropdown menus, they both open no matter which top level link you click. I think only the selected menu should open.
2. Also a style issue is that the links don't extend the full width of the menu but should, which is noticeable on hover or focus

<img width="259" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/a823c527-a1bd-4280-9799-d6bcde8b55dd">

2024-07-08 22:25 UTC, adriencyberspace commented on app/components/ui/Navigation.tsx
> +  };
Works for me. You could also use a `switch` but not a big deal with only 3 cases.

2024-07-08 22:40 UTC, adriencyberspace commented
I think we should hide mobile on desktop size screens. i.e. if I open it on a smaller screen, it should disappear when I make my screen larger.

<img width="356" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/bddcec28-11ad-44f4-8c8e-6468412d9d5b">

2024-07-09 18:11 UTC, rosschapman commented
@adriencyberspace my latest [commit](https://github.com/Exygy/askdarcel-web/pull/75/commits/818c85dd462e9554d52dddeee9bc74f91f7106cb) fixes the issues with multiple _Navigation Menu_ types in the nav. Regarding  https://github.com/Exygy/askdarcel-web/pull/75#issuecomment-2215471398 I propose we consider that in a polish phase. I'd like to better understand the scenario of a user resizing their browser that much. 

Please take another look thank you!

https://github.com/Exygy/askdarcel-web/assets/5185/79c017b1-94bc-483e-b05a-adf50f13665f

2024-07-09 18:18 UTC, adriencyberspace commented
@rosschapman Off the bat, I'm seeing that the top level and single level links do not have uniform styling but do in the mockup. 

Actual:
<img width="390" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/99194ed4-90fa-4ccb-8da1-34d5951f64fc">

Mockup:
<img width="401" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/07a801fa-f6d6-49e7-acb4-44db42fc2d6d">

Aside from that, can you make the mobile absolute positioned? I know it came in from SF Service Finder, but I can't recall seeing a mobile nav that pushes content over on any other site and I think it affects UX.

2024-07-09 18:20 UTC, adriencyberspace commented
I also still think these links should be full container width:

<img width="202" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/24b6b0b3-956b-4fd1-aafb-52e2c5f07880">

2024-07-09 18:46 UTC, rosschapman commented
@adriencyberspace These are fixed with https://github.com/Exygy/askdarcel-web/pull/75/commits/7d5efd2cb8b08af49d4b386eadaa9204f5150751
- [ ] https://github.com/Exygy/askdarcel-web/pull/75#issuecomment-2218366138
- [ ] https://github.com/Exygy/askdarcel-web/pull/75#issuecomment-2218366138

Regarding doing a slide-out vs push-out nav...hmmm. That will be a bit more involved. Let's park that for another iteration. I'll need to get some more design guidance on that to figure out how the overlay control looks/works.

2024-07-10 17:32 UTC, adriencyberspace approved these changes
LGTM! Two minor visual QA changes before merging:

1. Single tier item on mobile is not same font weight as two tiered
<img width="364" alt="image" src="https://github.com/Exygy/askdarcel-web/assets/60076088/70e2b6d1-7e7f-448c-a141-89b7a2ee530a">
2. Single tier item on desktop does not have same hover color as two tiered

2024-07-10 18:57 UTC, merged